### ISSUE TITLE
The game closes before you can see the reults of the last turn.

### ISSUE THREAD

**Issue by dcoollx** [ketanhwr/chain-reaction#21]
As it is now, as soon as the script determines the winner, the screen is cleared and a new game starts. it would be nice if you could see why you won/lose before it starts over. this could possibly be addressed by changing the check for game over to the START of the game loop rather than the end.

**Comment by ketanhwr** [comment]
Thanks! :+1:

If you want you can solve this as well!

**Comment by NithinBiliya** [comment]
@ketanhwr master branch to be synched with gh-pages for this fix to reflect in the demo

**Comment by ketanhwr** [comment]
Thanks for reminding :slightly_smiling_face:
