### ISSUE TITLE
undo button visible and clickable when showing the game result

### ISSUE THREAD

**Issue by NithinBiliya** [ketanhwr/chain-reaction#23]
undo button visible and clickable when showing the game result

**Comment by ketanhwr** [comment]
If you want you can work on this, it's quite simple! :slightly_smiling_face:

**Comment by NithinBiliya** [comment]
ok let me fix this. will just hide the undo div till the next game starts

**Comment by chrised123** [comment]
@NithinBiliya is this still open?

**Comment by ketanhwr** [comment]
@chrised123 thanks for reminding me to close this one.

**Comment by NithinBiliya** [comment]
@ketanhwr master branch to be synched with gh-pages for this fix to reflect in the demo

**Comment by ketanhwr** [comment]
Thanks for reminding :slightly_smiling_face:

**Comment by NithinBiliya** [comment]
:thumbsup:
